### ISSUE TITLE
Cannot tag Irredemable

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#11]
_From [apastus...@gmail.com](https://code.google.com/u/116932197388107485187/) on April 03, 2013 06:23:17_

What steps will reproduce the problem? 1. Launch ComicTagger
2. Try and tag an irredemable CBZ files 3. What is the expected output? What do you see instead? I get the follow error:

\--------------------------------------------------
-----> Irredeemable (2009) `#22` None (02/2011) -- score: 0
\--------------------------------------------------
Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in \<module>
  File "\Users\tony/Dropbox/tagger/comictagger\comictagger.py", line 5, in \<modu
le>
  File "\Users\tony/Dropbox/tagger/comictagger\comictaggerlib\main.py", line 54,
 in ctmain
  File "\Users\tony/Dropbox/tagger/comictagger\comictaggerlib\cli.py", line 184,
 in cli_mode
  File "\Users\tony/Dropbox/tagger/comictagger\comictaggerlib\cli.py", line 421,
 in process_file_cli
  File "\Users\tony/Dropbox/tagger/comictagger\comictaggerlib\cli.py", line 67,
in actual_issue_data_fetch
  File "\Users\tony/Dropbox/tagger/comictagger\comictaggerlib\comicvinetalker.py
", line 281, in fetchIssueData
  File "\Users\tony/Dropbox/tagger/comictagger\comictaggerlib\comicvinetalker.py
", line 314, in mapCVDataToMetadata
  File "C:\Python27\lib\re.py", line 151, in sub
    return _compile(pattern, flags).sub(repl, string, count)
TypeError: expected string or buffer What version of the product are you using? On what operating system? 1.15 beta on Windows 7 64 bit Please provide any additional information below.

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=11_

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on April 02, 2013 23:14:34_

The Comic Vine API changed under our feet again, and this is the result of an issue title not being present and the code not checking for it.  A new release will be out this week to fix this.

**Comment by davide-romanini** [comment]
_From [apastus...@gmail.com](https://code.google.com/u/116932197388107485187/) on April 03, 2013 04:18:14_

They must have changed  it right in the middle of my tagging, because  Uncanny X-Men tagged fine, and then everything after it stopped working.

BTW, my name is not tony.  Are there some hardcoded paths that the python compiler is making?

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on April 03, 2013 10:34:27_

If you're tagging issues that have a title, it probably will still work.  

The way the Windows and Mac binaries are made "freezes" the python module files into an executable along with the python interpreter.  The paths you are seeing from my Windows build machine.

**Comment by davide-romanini** [comment]
_From [sas...@gmail.com](https://code.google.com/u/101368042270943327607/) on April 03, 2013 12:37:01_

In case you miss it, there is the same problem in performQuery in issueselectionwindow.py with empty  record['name']

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on April 03, 2013 12:38:53_

Just uploaded 1.1.6-beta.  Give it a whirl, and post back.

**Comment by davide-romanini** [comment]
_From [sas...@gmail.com](https://code.google.com/u/101368042270943327607/) on April 03, 2013 12:44:43_

Both working now auto-tag and issues selection window, thank you. 

All is well again - comic book day may now proceed.

**Comment by davide-romanini** [comment]
_From [apastus...@gmail.com](https://code.google.com/u/116932197388107485187/) on April 03, 2013 13:06:04_

I'll check when I get home, unless you feel like coding some authenticated proxy support in the next 20 minutes.  :-)

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on April 04, 2013 09:02:12_

**Status:** Fixed
