### ISSUE TITLE
GUI hang on Fetch Info, CLI reports Error

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#13]
_From [ShadowRa...@gmail.com](https://code.google.com/u/102621413130037826735/) on April 20, 2013 19:46:24_

What steps will reproduce the problem? 1. Attempt search for 2000 AD Issue 878 in GUI or in CLI What is the expected output? What do you see instead? Expected to see tags / info for issue. Hangs in GUI, Error in CLI What version of the product are you using? On what operating system? v1.1.3 beta Please provide any additional information below. CLI command attempted:

ComicTagger -s -o -v -m "series=2000 AD,issue=878" -n -t cbl ~/19940311\ 2000\ AD\ Prog\ 878.cbz 

Output:

Going to search for:
	Series: 2000 AD
	Issue : 878
	Year :  1994
	Month : 3
Searching for  2000 AD `#878` ...
Searching in 1 series
Fetching info for  ID: 19752 2000 AD (1977) ...
Traceback (most recent call last):
  File "<string>", line 5, in \<module>
  File "/Users/tony/Dropbox/tagger/comictagger/mac/build/pyi.darwin/ComicTagger/out00-PYZ.pyz/comictaggerlib.main", line 54, in ctmain
  File "/Users/tony/Dropbox/tagger/comictagger/mac/build/pyi.darwin/ComicTagger/out00-PYZ.pyz/comictaggerlib.cli", line 184, in cli_mode
  File "/Users/tony/Dropbox/tagger/comictagger/mac/build/pyi.darwin/ComicTagger/out00-PYZ.pyz/comictaggerlib.cli", line 376, in process_file_cli
  File "/Users/tony/Dropbox/tagger/comictagger/mac/build/pyi.darwin/ComicTagger/out00-PYZ.pyz/comictaggerlib.issueidentifier", line 456, in search
  File "/Users/tony/Dropbox/tagger/comictagger/mac/build/pyi.darwin/ComicTagger/out00-PYZ.pyz/comictaggerlib.comicvinetalker", line 328, in fetchIssueDate
  File "/Users/tony/Dropbox/tagger/comictagger/mac/build/pyi.darwin/ComicTagger/out00-PYZ.pyz/comictaggerlib.comicvinetalker", line 364, in fetchIssueSelectDetails
KeyError: 'publish_year'

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=13_

**Comment by davide-romanini** [comment]
_From [ShadowRa...@gmail.com](https://code.google.com/u/102621413130037826735/) on April 20, 2013 10:48:09_

PS not sure what all the Users/tony/Dropbox stuff is all about... my local username is megan...
PPS the app was downloaded from https://code.google.com/p/comictagger/downloads/detail?name=ComicTagger-1.1.7-beta.dmg&can=2&q=

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on April 21, 2013 09:47:12_

This error has been fixed since 1.1.3-beta.  Sounds like you're not running the most recent version that you've downloaded. Can you double-check?

**Comment by davide-romanini** [comment]
_From [ShadowRa...@gmail.com](https://code.google.com/u/102621413130037826735/) on April 21, 2013 10:36:28_

Thanks - I didn't notice when I went to get the download link that the version was different from what I was running.
Sorry for taking up your time - I feel like such a noob [don't worry - it'll pass ;-) ]
Yes the 1.1.7 version works great
Keep up the great work!!

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on April 21, 2013 17:59:28_

No prob.  Glad this was so easy to fix :-)

**Status:** Fixed
