### ISSUE TITLE
using source, I get the following when trying to read CBL from a file

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#2]
_From [m...@themaxx.ca](https://code.google.com/u/102413495307761203345/) on December 04, 2012 22:55:06_

File is CBZ
following is a copy paste of my console:

mypromt:comictagger-src-0.9.0-beta me$ ./comictagger.py -p -t cbl "/Users/me/Documents/comics/somecomic/Some Comic V2010 01 (2010).cbz" 
------ComicBookLover tags--------
Traceback (most recent call last):
  File "./comictagger.py", line 364, in \<module>
    main()
  File "./comictagger.py", line 338, in main
    cli_mode( opts, settings )
  File "./comictagger.py", line 59, in cli_mode
    process_file_cli( f, opts, settings )
  File "./comictagger.py", line 120, in process_file_cli
    print u"{0}".format(ca.readCBI())
  File "/Users/me/Downloads/comictagger-src-0.9.0-beta/genericmetadata.py", line 246, in __str__
    for c in self.credits:
TypeError: 'NoneType' object is not iterable

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=2_

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on December 04, 2012 16:22:39_

Whoops.  I am guess you made this from CBL, which I never did.  Anyways, fixed the case of an non-existing internal credits list.  Fixed checked in to comicbookinfo.py

**Status:** Fixed
