### ISSUE TITLE
App crashes when attempting to use the open file/open folder function 

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#32]
_From [mtlupe...@gmail.com](https://code.google.com/u/102366029290799416026/) on October 16, 2013 06:31:17_

What steps will reproduce the problem? 1. Launch executable file 2. 3. What is the expected output? What do you see instead? Expected: App, GUI
Instead: DOS window with the following output, then the app terminates with no further message/output:

Traceback (most recent call last):
  File "C:\Python27\lib\site-packages\cx_Freeze\initscripts\Console.py", line 27
, in <module>
  File "\Users\tony/Dropbox/tagger/comictagger\comictagger.py", line 5, in <modu
le>
  File "\Users\tony/Dropbox/tagger/comictagger\comictaggerlib\main.py", line 42,
 in ctmain
  File "\Users\tony/Dropbox/tagger/comictagger\comictaggerlib\settings.py", line
 139, in **init**
  File "\Users\tony/Dropbox/tagger/comictagger\comictaggerlib\settings.py", line
 181, in load
  File "C:\Python27\lib\site-packages\configparser.py", line 728, in read_file
  File "C:\Python27\lib\site-packages\configparser.py", line 1116, in _read
configparser.MissingSectionHeaderError: File contains no section headers.
file: <???>, line: 1
u'\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x
00\x00\x00\x00\x00\x00' What version of the product are you using? On what operating system? v1.1.9 beta on Windows XP Home Edition Please provide any additional information below. App has worked on this same computer/OS before, unsure exactly which version.  I ran it earlier this evening, encountered the above output, then...

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=32_

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on October 20, 2013 15:45:51_

Looks like the settings file got corrupted somehow.    In explorer you should be able to use "%APPDATA%\Comictagger" to navigate to the folder, and the file is called "settings".  (I think that will work in XP...).  Make a copy of the file, maybe called "settings.copy", and then delete the original.  Try running CT again, hopefully the problem has gone away.

Either way, can you attach the copy file here?  Thanks!

**Status:** Accepted

**Comment by davide-romanini** [comment]
_From [mtlupe...@gmail.com](https://code.google.com/u/102366029290799416026/) on October 20, 2013 18:13:30_

Followed instructions...CT launched like a champ!  Here's the culprit:

**Attachment:** [settings.copy](http://code.google.com/p/comictagger/issues/detail?id=32#hc2)

**Comment by davide-romanini** [comment]
_From [mtlupe...@gmail.com](https://code.google.com/u/102366029290799416026/) on October 20, 2013 19:32:31_

Okay...new issue (and I can start a new thread if it appears unrelated):  all app functions seem to be working fine, but now clicking on the "OPEN"/"OPEN FOLDER" buttons or choosing those actions in the "File" menu cause the UI and DOS to immediately shut down.  Dragging-and-dropping folders/files works and is now the only way to open them in the app.

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 25, 2014 15:22:33_

Did this issue persist?  I'm thinking it was probably some kind of disk corruption that messed up the app files.  

I don't hear back, I will close this as "can't reproduce"

**Comment by davide-romanini** [comment]
_From [mtlupe...@gmail.com](https://code.google.com/u/102366029290799416026/) on March 25, 2014 15:27:49_

I've recently updated the app and continued to use it, however I am still
only able to open archives by dragging-and-dropping.  The File/Open option
still causes the app to shut down.  I will update next time I launch the
app (before midnight EST).  Thanks!

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 25, 2014 15:35:08_

Thanks for the response after such a long time.

This is a very odd error.  But maybe many people aren't using XP.  I've only been building and testing on Windows 7

Just curious, what's your username the XP system?  I recently found a bug where there needed to be character set decoding that wasn't being done.  Also, what's the path of a folder that you keep comics in?  Any non-english characters?

**Summary:** App crashes when attempting to use the open file/open folder function   \<span class="oldvalue"> (was: App will no longer launch) \</span>

**Comment by davide-romanini** [comment]
_From [mtlupe...@gmail.com](https://code.google.com/u/102366029290799416026/) on March 26, 2014 19:04:40_

Hey!  Sorry for the delay.  Here's the latest, effective as of v1.1.12-beta:

- Username is "Michael"
- Comics are stored in local public folder w/subdirectories.  All names are standard characters.
- Initial bug remains resolved.  Bug described in comment `#3` above persists.  A copy of the latest "settings.copy" is attached.
- App DOES continue to work with no problems as long as I drag-and-drop files or folders into it.

**Attachment:** [settings.copy](http://code.google.com/p/comictagger/issues/detail?id=32#hc7)

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 27, 2014 12:26:40_

Since this is an XP machine, I am going to get that the OS was installed some time ago, and cruft can accumulate, especially when you've installed and un-installed lots of apps over the years.  I wonder if for some reason, there are other Qt related DLLs that ComicTagger is somehow finding, but they're not really compatable, hence the weird behavior.

Another experiment idea:  create a new user on the computer, and then try to run comictagger as that user.

**Comment by davide-romanini** [comment]
I'll not support XP. Closing.
