### ISSUE TITLE
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbd' in position 59: ordinal not in range(128)

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#34]
_From [olin...@gmail.com](https://code.google.com/u/117177305437248657771/) on December 05, 2013 23:23:34_

What steps will reproduce the problem? 1. comictagger.py -v -e --delete-rar Darkchylde\ Redemption\ 0\ ½\ --\ \[\]\[DC\].cbr What is the expected output? What do you see instead? Traceback (most recent call last):
  File "/usr/local/bin/comictagger.py", line 5, in \<module>
    ctmain()
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/main.py", line 54, in ctmain
    cli.cli_mode( opts, settings )
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/cli.py", line 184, in cli_mode
    process_file_cli( f, opts, settings, match_results )
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/cli.py", line 505, in process_file_cli
    if ca.exportAsZip( new_file ):
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/comicarchive.py", line 1044, in exportAsZip
    return zip_archiver.copyFromArchive( self.archiver )
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/comicarchive.py", line 225, in copyFromArchive
    print >> sys.stderr, "Error while copying to {0}: {1}".format(self.path, e)
UnicodeEncodeError: 'ascii' codec can't encode character u'\xbd' in position 59: ordinal not in range(128) What version of the product are you using? On what operating system? 1.1.9, Ubuntu 12.10 Please provide any additional information below. I suspect comictagger doesn't like the ½ (Unicode?) character in the filename.

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=34_

**Comment by davide-romanini** [comment]
_From [olin...@gmail.com](https://code.google.com/u/117177305437248657771/) on December 07, 2013 02:45:05_

I confirmed the ComicTagger GUI will pull the 1/2 Unicode character from ComicVine fine. For example look up the first issue of "Tommi Gunn" (London Night Studios; the actual date is 11/96 but ComicVine doesn't have it) listed as issue "1/2".

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 22, 2014 13:34:39_

Finally looked into this one.  Should be fixed with next release

**Status:** Accepted

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 25, 2014 15:23:20_

**Status:** Fixed
