### ISSUE TITLE
Exceptions during batch tasks abort the program

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#6]
_From [svi...@gmail.com](https://code.google.com/u/114997901959681192937/) on February 20, 2013 09:51:14_

What steps will reproduce the problem? 1. Run a batch task, such as comictagger.py -t cr -s -o -f *
2. Encounter an exception, such as a PIL IOError
3. Program aborts immediately What is the expected output? What do you see instead? It should skip the file encountering the error, instead of aborting entirely. What version of the product are you using? On what operating system? comictagger 1.1.2
Ubuntu 12.04
Python 2.7.3 Please provide any additional information below. Traceback (most recent call last):
  File "/usr/local/bin/comictagger.py", line 5, in \<module>
    ctmain()
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/main.py", line 54,                              in ctmain
    cli.cli_mode( opts, settings )
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/cli.py", line 184,                              in cli_mode
    process_file_cli( f, opts, settings, match_results )
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/cli.py", line 376,                              in process_file_cli
    matches = ii.search()
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/issueidentifier.py                             ", line 349, in search
    right_side_image_data = self.cropCover( cover_image_data )
  File "/usr/local/lib/python2.7/dist-packages/comictaggerlib/issueidentifier.py                             ", line 139, in cropCover
    cropped_im.save(output, format="JPEG")
  File "/usr/lib/python2.7/dist-packages/PIL/Image.py", line 1439, in save
    save_handler(self, fp, filename)
  File "/usr/lib/python2.7/dist-packages/PIL/JpegImagePlugin.py", line 425, in _                             save
    raise IOError("cannot write mode &#37;s as JPEG" &#37; im.mode)
IOError: cannot write mode P as JPEG

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=6_

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on February 20, 2013 08:22:00_

Looks like the archive contains palletized images, something I never thought of.  Can you share a link to the archive, or mail it to me at comictagger@gmail.com?  Should be easy to fix out once I can play with it.

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 27, 2013 17:09:39_

**Status:** Fixed
