### ISSUE TITLE
Cannot Install ComicTagger on Fedora 18

### ISSUE THREAD

**Issue by davide-romanini** [davide-romanini/comictagger#8]
_From [apastus...@gmail.com](https://code.google.com/u/116932197388107485187/) on March 29, 2013 03:47:01_

What steps will reproduce the problem? 1. Install Fedora 18 64 bit
2. Install ComicTagger
3. Run comictagger.py What is the expected output? What do you see instead? I expect to see ComicTagger launch.  Instead I see this:

Traceback (most recent call last):
  File "/usr/bin/comictagger.py", line 2, in \<module>
    from comictaggerlib.main import ctmain
  File "/usr/lib/python2.7/site-packages/comictaggerlib/main.py", line 28, in \<module>
    import cli
  File "/usr/lib/python2.7/site-packages/comictaggerlib/cli.py", line 35, in \<module>
    from settings import ComicTaggerSettings
  File "/usr/lib/python2.7/site-packages/comictaggerlib/settings.py", line 24, in \<module>
    import configparser What version of the product are you using? On what operating system? 1.1.4beta on Fedora 18 64-bit Please provide any additional information below. I'm sure I'm just missing some Python stuff, but any help would be appreciated.

_Original issue: http://code.google.com/p/comictagger/issues/detail?id=8_

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 28, 2013 20:33:08_

You need to install the python package "configparser". I don't know Fedora, but I assume you can use easy_install or pip to do it.

**Comment by davide-romanini** [comment]
_From [apastus...@gmail.com](https://code.google.com/u/116932197388107485187/) on March 28, 2013 21:08:03_

That did it!  Thanks!

**Comment by davide-romanini** [comment]
_From [bevi...@gmail.com](https://code.google.com/u/113985037434965044185/) on March 29, 2013 19:27:23_

**Status:** Done
