### ISSUE TITLE
Could not connect to ComicVine for Search and API test

### ISSUE THREAD

**Issue by viperomegax** [davide-romanini/comictagger#81]
I am using the ComicTagger v1.1.15-beta GUI for Windows (8.1 Pro).

Today was the first day I tried this fantastic application and it was working flawlessly until it stopped.

First I noticed when attempting to Search Online or Auto-Identify I would receive "Could not connect to ComicVine to search for series!"

In the command prompt there is an entry "HTTP Error 403: Forbidden"

Assuming I may have exceeded my calls to ComicVine for the day (i checked on their website and I am ok) I attempted to test the API Key. Nothing seems to happen and the following entry is displayed in the command  prompt:

Traceback (most recent call last):
  File "\Users\tony/Dropbox/tagger/comictagger\comictaggerlib\settingswindow.py", line 223, in testAPIKey
  File "\Users\tony/Dropbox/tagger/comictagger\comictaggerlib\comicvinetalker.py", line 132, in testKey
  File "C:\Python27\lib\urllib2.py", line 126, in urlopen
  File "C:\Python27\lib\urllib2.py", line 406, in open
  File "C:\Python27\lib\urllib2.py", line 519, in http_response
  File "C:\Python27\lib\urllib2.py", line 444, in error
  File "C:\Python27\lib\urllib2.py", line 378, in _call_chain
  File "C:\Python27\lib\urllib2.py", line 527, in http_error_default
urllib2.HTTPError: HTTP Error 403: Forbidden

Thank You for your assistance!

**Comment by viperomegax** [comment]
This appears to have resolved its self approximately 24 hours after it stopped. Even though I have my own API key, is there something else built in to throttle requests or provide a 24 hour block on requests?

**Comment by davide-romanini** [comment]
It could be related to this?
http://comicvine.gamespot.com/forums/api-developers-2334/am-i-blocked-1714639/

I admit I really don't know enough the comicvine part of comictagger. I will look better in the future.
